### ISSUE TITLE
Code in rvv_test/intrinsic fails to compile

### ISSUE THREAD

**Issue by KGback** [compiler-dev/llvm-rv#11]
Hello，I have a problem about compiling，I succeeded when compiling rvv-test/vadd_vv_i32.c，but when compiling rvv-test/intrinsic/vadd_vv_i8.c, It was failed：**error: unknown type name 'vint8m2_t'；did you mean 'vint8m1_t'?**  And there is one note: **'vint8m1_t' declared here  typedef __attribute__((riscv_vector_type(16))) int8_t vint8m1_t;** 
So how can I solve this problem？

**Comment by dingchuanxin** [comment]
Thanks for reporting this issue. The last commit a0699d has fixed it.
